project:
  type: website
  

highlight-style: a11y


website:
  site-url: "https://stesiam.com"
  repo-url: "https://github.com/stesiam/stesiam.github.io"
  page-footer:
    left: "Φιλοξενείται μέσω του <i class='bi bi-github'></i> GitHub Pages <br> <i class='bi bi-code-slash'></i> [Κώδικας ιστοσελίδας](https://github.com/stesiam/stesiam.github.io)"
    center: "&#169; stesiam, 2022-2026"
    right: "Δημιουργήθηκε με το λογισμικό [Quarto](https://quarto.org/), το 
            πακέτο [babelquarto](https://github.com/ropensci-review-tools/babelquarto),<br> αρκετή αγάπη και υπομονή"
  navbar:
    tools:
      - icon: github
        href: https://github.com/stesiam
        aria-label: Σύνδεσμος για το προφίλ μου στο GitHub (stesiam)
      - icon: rss
        href: posts/index.xml
        aria-label: Το RSS για τα άρθρα της ιστοσελίδας, ώστε να ενημερώνεται ο αναγνώστης για νέα άρθρα
    right:
      - text: "Αρχική"
        aria-label: "Homepage"
        href: index.qmd
      - text: "Σχετικά"
        href: about-me/index.qmd
      - text: "Άρθρα"
        aria-label: "Συγκεντρωτική λίστα των άρθρων μου στα ελληνικά"
        href: posts/index.qmd
      - text: "Εφαρμογές"
        href: web-projects/index.qmd
      - text: "Λογισμικό"
        href: software/index.qmd
      - text: "Υλικό"
        href: material/index.qmd
      - text: "Γραφήματα"
        href: gallery/index.qmd
      - text: "CV"
        href: https://github.com/stesiam/cvDSen


format:
  html:
    theme: 
      light: [assets/li.scss]
      dark: [assets/da.scss]
    css: assets/styles/styles.css
    toc: true
    html-math-method: katex
    clean-urls: false
    comments:
      giscus:
        repo: stesiam/stesiam.github.io
        repo-id: R_kgDOHuiNDg
        category: Comments
        category-id: DIC_kwDOHuiNDs4CQeAf
        mapping: title
        reactions-enabled: true
        input-position: top
        theme:
          light: light
          dark: dark
        language: gr
