project:
  type: website

website:
  page-footer:
    left: "Φιλοξενείται μέσω του <i class='bi bi-github'></i> GitHub Pages <br> <i class='bi bi-code-slash'></i> [Κώδικας ιστοσελίδας](https://github.com/stesiam/stesiam.github.io)"
    center: "&#169; stesiam, 2022-2025"
    right: "Χρησιμοποιήθηκε η γλώσσα προγραμματισμού R (Rstats),<br>το λογισμικό [Quarto](https://quarto.org/), το 
            πακέτο [babelquarto](https://github.com/ropensci-review-tools/babelquarto),<br> αρκετή αγάπη και υπομονή"
  navbar:
    tools:
      - icon: github
        href: https://github.com/stesiam
        aria-label: Σύνδεσμος για το προφίλ μου στο GitHub (stesiam)
      - icon: rss
        href: posts/index.xml
        aria-label: Το RSS για τα άρθρα της ιστοσελίδας, ώστε να ενημερώνεται ο αναγνώστης για νέα άρθρα
    right:
      - text: "Αρχική"
        aria-label: "Homepage"
        href: index.qmd
      - text: "Άρθρα"
        aria-label: "Συγκεντρωτική λίστα των άρθρων μου στα ελληνικά"
        href: posts/index.qmd
      - text: "Εφαρμογές"
        href: web-apps/index.qmd
      - text: "Λογισμικό"
        href: software/index.qmd
      - text: "Υλικό"
        href: material/index.qmd
      - text: "Γραφήματα"
        href: gallery/index.qmd
      - text: "CV"
        href: https://github.com/stesiam/cvDSen


format:
  html:
    theme: 
      light: [litera, assets/styles/stesiam-light.scss]
      dark: [litera, assets/styles/stesiam-dark.scss]
    css: assets/styles/styles.css
    highlight-style: 
      light: assets/styles/a11y-light.theme
      dark: assets/styles/a11y-dark.theme
    toc: true
    html-math-method: katex
    comments:
      giscus:
        repo: stesiam/stesiam.github.io
        repo-id: R_kgDOHuiNDg
        category: Comments
        category-id: DIC_kwDOHuiNDs4CQeAf
        mapping: title
        reactions-enabled: true
        input-position: top
        theme:
          light: light
          dark: dark
        language: gr
